#!/usr/bin/env bash
# scripts/generate-pricing-rules.sh — generate Prometheus recording rules from the pricing table
#
# Usage:
#   ./scripts/generate-pricing-rules.sh            # print generated YAML to stdout
#   ./scripts/generate-pricing-rules.sh --write    # write to configs/prometheus/rules/pricing-generated.yaml
#
# Reads configs/pricing/model-prices.json (USD per 1M tokens per model) and emits one
# `shepherd:model_price:usd_per_mtok` recording rule per model x token-type, labeled with
# `model` and `type` so it joins against shepherd_session_tokens_total{model,type}.
#
# Deterministic: rule order follows the JSON file's model order, then a fixed type order
# (input, output, cacheRead, cacheCreation) — so `diff <(generate) committed-file` is a valid
# sync check between the pricing table and the committed generated rules file.
#
# Dependencies: jq

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PRICING_FILE="$REPO_ROOT/configs/pricing/model-prices.json"
OUTPUT_FILE="$REPO_ROOT/configs/prometheus/rules/pricing-generated.yaml"

generate() {
  printf '%s\n' \
    '# GENERATED by scripts/generate-pricing-rules.sh from configs/pricing/model-prices.json — DO NOT EDIT' \
    'groups:' \
    '  - name: shepherd_model_prices' \
    '    interval: 1m' \
    '    rules:'

  jq -r '
    .prices[] as $p |
    ["input","output","cacheRead","cacheCreation"][] as $t |
    "      - record: shepherd:model_price:usd_per_mtok\n" +
    "        expr: label_replace(label_replace(vector(\($p[$t])), \"model\", \"\($p.model)\", \"\", \"\"), \"type\", \"\($t)\", \"\", \"\")"
  ' "$PRICING_FILE"
}

if [[ "${1:-}" == "--write" ]]; then
  generate > "$OUTPUT_FILE"
  echo "wrote $OUTPUT_FILE" >&2
else
  generate
fi
